# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b71eb9af628918030d989ef8f429da8cbfbd31b7cfacbd016b5ddb3b45124dd2e11aba4183e3f0ce69c93c399f019fecb1c560baac0df229141ea287ca980a

test:
  secret_key_base: c0d43e7b0cce8b11ffad63e024a883b22cba0b4b53460fad4e6a76f64ae80ede01c230f466154aadf93492963916c88cec7613e8e4d8600c58aadd18b9166da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
